import fs from 'fs';
const xml = fs.readFileSync('.tmp-workerD/content-sitemap.xml', 'utf8');
const locs = [...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map((m) => m[1]);
fs.writeFileSync('.tmp-workerD/urls.json', JSON.stringify(locs));
const travel = locs.filter((u) => u.includes('/travel/')).map((u) => u.replace('https://aifanyi.com', ''));
const life = locs.filter((u) => u.includes('/life/')).map((u) => u.replace('https://aifanyi.com', ''));
console.log('TRAVEL', travel.length);
console.log(travel.join('\n'));
console.log('LIFE', life.length);
console.log(life.slice(0, 12).join('\n'));
const memeCount = locs.filter((u) => u.includes('/meme/')).length;
const idiomCount = locs.filter((u) => u.includes('/idioms/')).length;
const untrCount = locs.filter((u) => u.includes('/untranslatable/')).length;
console.log('MEME', memeCount, 'IDIOM', idiomCount, 'UNTR', untrCount);
