// 梗词条种子数据（200 条）— 数据源文件
// 由 seed.ts 批量 upsert 入库；slug 用于 SEO 页 URL
export interface MemeSeed {
  term: string;
  slug: string;
  meaning: string;
  translation: string;
  examples: { zh: string; en: string }[];
  tags: string[];
  popularity: number;
}

export const memeData: MemeSeed[] = [
  { term: 'YYDS', slug: 'yyds', meaning: '永远的神，表达极度赞叹', translation: 'God-tier', examples: [{ zh: '这个耳机降噪效果 YYDS！', en: 'The noise cancelling on these headphones is God-tier!' }], tags: ['感叹', '缩写'], popularity: 100 },
  { term: '栓Q', slug: 'shuan-q', meaning: 'thank you 谐音，常带无语/无奈语气', translation: 'Thanks... I guess', examples: [{ zh: '栓Q，又是周一。', en: 'Thanks, I guess. Monday again.' }], tags: ['谐音', '反讽'], popularity: 95 },
  { term: '绝绝子', slug: 'juejuezi', meaning: '绝了，极度好评', translation: 'Absolutely stunning', examples: [{ zh: '这家店的小蛋糕绝绝子！', en: 'The cakes at this shop are absolutely stunning!' }], tags: ['感叹'], popularity: 92 },
  { term: '破防了', slug: 'pofangle', meaning: '心理防线被击穿，被感动或戳中', translation: 'That hit me right in the feels', examples: [{ zh: '看到那段视频直接破防了。', en: 'That video hit me right in the feels.' }], tags: ['情绪'], popularity: 90 },
  { term: '躺平', slug: 'tangping', meaning: '放弃内卷，低欲望生活', translation: 'Lie flat', examples: [{ zh: '我不想卷了，我要躺平。', en: "I'm done grinding — I'm going to lie flat." }], tags: ['生活态度'], popularity: 88 },
  { term: '内卷', slug: 'neijuan', meaning: '同行过度竞争，付出多回报少', translation: 'Rat race / involution', examples: [{ zh: '现在连实习都开始内卷了。', en: 'Even internships have become a rat race now.' }], tags: ['社会现象'], popularity: 86 },
  { term: '社死', slug: 'shesi', meaning: '社会性死亡，当众出丑', translation: 'Died of cringe', examples: [{ zh: '在年会上叫错老板名字，当场社死。', en: 'I called my boss by the wrong name at the annual party — died of cringe.' }], tags: ['社交'], popularity: 84 },
  { term: 'emo', slug: 'emo', meaning: '情绪低落、伤感', translation: 'In my feels', examples: [{ zh: '深夜听歌容易 emo。', en: 'Listening to music late at night gets me in my feels.' }], tags: ['情绪'], popularity: 82 },
  { term: '芭比Q了', slug: 'barbecue', meaning: '完蛋了（完犊子谐音）', translation: "We're cooked", examples: [{ zh: '手机掉水里，芭比Q了。', en: 'My phone fell in the water — we are cooked.' }], tags: ['谐音', '无奈'], popularity: 80 },
  { term: '拿捏', slug: 'nanie', meaning: '掌控、搞定', translation: 'Nailed it', examples: [{ zh: '这个项目的节奏我已经拿捏了。', en: "I've got the rhythm of this project down." }], tags: ['职场'], popularity: 78 },
  { term: 'xswl', slug: 'xswl', meaning: '笑死我了（拼音首字母缩写）', translation: 'LMAO / I am dying', examples: [{ zh: '这个视频 xswl。', en: 'This video is hilarious, I am dying.' }], tags: ['缩写', '大笑'], popularity: 94 },
  { term: 'nsdd', slug: 'nsdd', meaning: '你说得对（拼音缩写）', translation: 'You are so right', examples: [{ zh: 'nsdd，就这么办。', en: 'You are so right, let us do that.' }], tags: ['缩写'], popularity: 88 },
  { term: 'u1s1', slug: 'u1s1', meaning: '有一说一（谐音缩写）', translation: 'Gotta be honest / TBH', examples: [{ zh: 'u1s1，这家店真的好吃。', en: 'Gotta be honest, this place is really good.' }], tags: ['缩写', '表态'], popularity: 86 },
  { term: 'awsl', slug: 'awsl', meaning: '啊我死了，被萌到/被甜到', translation: "I'm dead (from cuteness)", examples: [{ zh: '猫猫也太可爱了，awsl！', en: 'That kitten is too cute — I am dead!' }], tags: ['缩写', '萌'], popularity: 90 },
  { term: 'dbq', slug: 'dbq', meaning: '对不起（拼音缩写）', translation: 'My bad / sorry', examples: [{ zh: 'dbq，我来晚了。', en: 'My bad, I am late.' }], tags: ['缩写'], popularity: 82 },
  { term: 'gkd', slug: 'gkd', meaning: '搞快点（拼音缩写）', translation: 'Hurry up!', examples: [{ zh: '别墨迹了，gkd！', en: 'Stop stalling, hurry up!' }], tags: ['缩写', '催促'], popularity: 84 },
  { term: 'plmm', slug: 'plmm', meaning: '漂亮妹妹（拼音缩写）', translation: 'Pretty girl', examples: [{ zh: '这个 plmm 是谁呀？', en: 'Who is that pretty girl?' }], tags: ['缩写', '夸赞'], popularity: 80 },
  { term: 'zqsg', slug: 'zqsg', meaning: '真情实感（拼音缩写）', translation: 'For real / genuinely', examples: [{ zh: '我对这部剧 zqsg 了。', en: 'I am genuinely invested in this show.' }], tags: ['缩写', '情绪'], popularity: 78 },
  { term: 'pyq', slug: 'pyq', meaning: '朋友圈（拼音缩写）', translation: 'Moments (WeChat feed)', examples: [{ zh: '看他在 pyq 晒的图。', en: 'Check the photos he posted on Moments.' }], tags: ['缩写', '社交'], popularity: 76 },
  { term: 'wdnmd', slug: 'wdnmd', meaning: '游戏里骂人首字母缩写（爆粗）', translation: 'WTF (rage quit phrase)', examples: [{ zh: '这队友太坑了，wdnmd。', en: 'This teammate is so bad, WTF.' }], tags: ['缩写', '游戏'], popularity: 72 },
  { term: '真香', slug: 'zhenxiang', meaning: '打脸现场：说不要结果还要', translation: 'The "it actually smells good" moment', examples: [{ zh: '他说绝不买，结果真香了。', en: 'He swore he would never buy it — guess what, he caved.' }], tags: ['打脸', '经典'], popularity: 89 },
  { term: '打脸', slug: 'dalian', meaning: '说大话被事实反驳', translation: 'Facepalm moment / get slapped', examples: [{ zh: '刚吹完牛就被打脸。', en: 'He bragged and immediately got slapped by reality.' }], tags: ['吐槽'], popularity: 83 },
  { term: '吃瓜', slug: 'chigua', meaning: '围观八卦、看热闹', translation: 'Spill the tea / watch the drama', examples: [{ zh: '别吵了，先吃瓜。', en: 'Stop arguing, let us just watch the drama.' }], tags: ['八卦'], popularity: 87 },
  { term: '冲浪', slug: 'chonglang', meaning: '上网刷信息', translation: 'Surfing the web', examples: [{ zh: '今天冲浪刷到好多瓜。', en: 'I surfed the web and found tons of drama today.' }], tags: ['网络'], popularity: 75 },
  { term: '上头', slug: 'shangtou', meaning: '上瘾、停不下来', translation: 'Obsessed / can not stop', examples: [{ zh: '这剧太上头了，熬夜刷完。', en: 'This show is so addictive, I binged it all night.' }], tags: ['情绪'], popularity: 85 },
  { term: '下头', slug: 'xiatou', meaning: '热情骤减、扫兴', translation: 'Kill the vibe', examples: [{ zh: '他一句话让我瞬间下头。', en: 'One sentence from him totally killed the vibe.' }], tags: ['情绪', '吐槽'], popularity: 80 },
  { term: '无语子', slug: 'wuyuzi', meaning: '无语（卖萌版）', translation: 'Speechless (cute way)', examples: [{ zh: '无语子，这也能错。', en: 'Speechless. How did you even mess that up?' }], tags: ['吐槽'], popularity: 77 },
  { term: '集美', slug: 'jimei', meaning: '姐妹的谐音（女生互称）', translation: 'Sis / bestie', examples: [{ zh: '集美们，冲鸭！', en: 'Sis, let us go!' }], tags: ['谐音', '称呼'], popularity: 79 },
  { term: '家人们', slug: 'jiarenmen', meaning: '直播间/视频里对观众亲昵称呼', translation: 'Hey fam / my people', examples: [{ zh: '家人们，这个真的便宜。', en: 'Hey fam, this is a real bargain.' }], tags: ['直播', '称呼'], popularity: 81 },
  { term: '老铁', slug: 'laotie', meaning: '东北方言：铁哥们、朋友', translation: 'Bro / buddy', examples: [{ zh: '老铁们，双击666！', en: 'Bro, smash that like button!' }], tags: ['方言', '称呼'], popularity: 85 },
  { term: '666', slug: '666', meaning: '厉害、牛（六六六）', translation: 'Sick! / Awesome!', examples: [{ zh: '这操作666啊！', en: 'That move was sick!' }], tags: ['夸赞', '数字'], popularity: 91 },
  { term: '杠精', slug: 'gangjing', meaning: '为杠而杠的人', translation: 'Professional contrarian', examples: [{ zh: '别跟杠精讲道理。', en: 'Do not reason with a professional contrarian.' }], tags: ['吐槽', '社交'], popularity: 82 },
  { term: '柠檬精', slug: 'ningmengjing', meaning: '爱酸别人的人', translation: 'Sour grapes / jealous hater', examples: [{ zh: '你就是个柠檬精。', en: 'You are just a jealous hater.' }], tags: ['吐槽'], popularity: 80 },
  { term: '戏精', slug: 'xijing', meaning: '爱加戏、浮夸表演的人', translation: 'Drama queen / attention seeker', examples: [{ zh: '别演了，戏精本精。', en: 'Stop it, you are such a drama queen.' }], tags: ['吐槽'], popularity: 78 },
  { term: '社恐', slug: 'shekong', meaning: '社交恐惧症', translation: 'Socially anxious', examples: [{ zh: '我是社恐，聚会能不去就不去。', en: 'I have social anxiety — I skip parties whenever I can.' }], tags: ['社交', '性格'], popularity: 84 },
  { term: '社牛', slug: 'sheniu', meaning: '社交牛逼症，自来熟', translation: 'Social butterfly / born extrovert', examples: [{ zh: '他社牛到跟陌生人聊一小时。', en: 'He is such a social butterfly, chatting with strangers for an hour.' }], tags: ['社交', '性格'], popularity: 80 },
  { term: '普信', slug: 'puxin', meaning: '普通却自信（多含贬义）', translation: 'Mediocre yet overly confident', examples: [{ zh: '他普信得让人窒息。', en: 'His confidence is way beyond his abilities — it is suffocating.' }], tags: ['吐槽'], popularity: 76 },
  { term: '绿茶', slug: 'lvcha', meaning: '表面清纯实则心机的女生', translation: 'Two-faced sweetheart', examples: [{ zh: '她可真是个绿茶。', en: 'She is such a two-faced sweetheart.' }], tags: ['吐槽', '恋爱'], popularity: 79 },
  { term: '白莲花', slug: 'bailianhua', meaning: '装无辜扮纯洁的人', translation: 'Innocent act / fake saint', examples: [{ zh: '别被她白莲花的样子骗了。', en: 'Do not be fooled by her innocent act.' }], tags: ['吐槽'], popularity: 74 },
  { term: '海王', slug: 'haiwang', meaning: '到处撩、广撒网的人', translation: 'Player / serial flirt', examples: [{ zh: '他就是个海王，别信他。', en: 'He is a total player, do not trust him.' }], tags: ['恋爱', '吐槽'], popularity: 82 },
  { term: '中央空调', slug: 'zhongyangkongtiao', meaning: '对谁都暖（多指渣男）', translation: 'Heater to everyone (a flirt)', examples: [{ zh: '他中央空调，对谁都好。', en: 'He is warm to everyone — a classic flirt.' }], tags: ['恋爱', '吐槽'], popularity: 75 },
  { term: '舔狗', slug: 'tiangou', meaning: '卑微讨好对方的人', translation: 'Simp / doormat', examples: [{ zh: '别再当舔狗了。', en: 'Stop being a simp.' }], tags: ['恋爱', '吐槽'], popularity: 86 },
  { term: '备胎', slug: 'beitai', meaning: '恋爱中的替补人选', translation: 'Backup / benchwarmer', examples: [{ zh: '他不过是我的备胎。', en: 'He is just my backup.' }], tags: ['恋爱'], popularity: 77 },
  { term: '养鱼', slug: 'yangyu', meaning: '同时吊着多个人', translation: 'Keeping options open', examples: [{ zh: '她同时在养鱼。', en: 'She is keeping multiple options open.' }], tags: ['恋爱'], popularity: 73 },
  { term: '官宣', slug: 'guanxuan', meaning: '正式公开（恋情等）', translation: 'Go public / official announcement', examples: [{ zh: '他俩官宣了！', en: 'They finally went public!' }], tags: ['恋爱', '追星'], popularity: 78 },
  { term: '秀恩爱', slug: 'xiuenai', meaning: '公开晒甜蜜', translation: 'PDA / flaunt love', examples: [{ zh: '别秀恩爱了，撒狗粮。', en: 'Stop with the PDA, you are feeding us dog food.' }], tags: ['恋爱'], popularity: 80 },
  { term: '撒狗粮', slug: 'sagouliang', meaning: '情侣秀恩爱虐单身狗', translation: 'Couple flaunting (to singles)', examples: [{ zh: '朋友圈又被撒狗粮了。', en: 'My feed is full of couple posts again.' }], tags: ['恋爱'], popularity: 76 },
  { term: '单身狗', slug: 'danshengou', meaning: '单身人士自嘲', translation: 'Forever alone / single', examples: [{ zh: '单身狗表示看不了这个。', en: 'As a single person, I cannot watch this.' }], tags: ['自嘲'], popularity: 79 },
  { term: '母胎solo', slug: 'mutai-solo', meaning: '从出生一直单身', translation: 'Single since birth', examples: [{ zh: '他母胎solo二十多年。', en: 'He has been single since birth for over 20 years.' }], tags: ['恋爱', '自嘲'], popularity: 72 },
  { term: '网恋', slug: 'wanglian', meaning: '网上恋爱', translation: 'Online romance', examples: [{ zh: '网恋有风险，奔现需谨慎。', en: 'Online romance is risky — meet in person with caution.' }], tags: ['恋爱'], popularity: 74 },
  { term: '奔现', slug: 'benxian', meaning: '网恋对象线下见面', translation: 'Meet in person (after online romance)', examples: [{ zh: '他们奔现成功了。', en: 'Their online romance worked out in person.' }], tags: ['恋爱'], popularity: 72 },
  { term: '见光死', slug: 'jianguangsi', meaning: '见面后幻想破灭', translation: 'The meetup killed the fantasy', examples: [{ zh: '一奔现就见光死。', en: 'The moment they met, the fantasy died.' }], tags: ['恋爱'], popularity: 71 },
  { term: '爷青回', slug: 'yeqinghui', meaning: '爷的青春回来了', translation: 'My childhood is back!', examples: [{ zh: '老歌重唱，爷青回！', en: 'They played the old songs again — my childhood is back!' }], tags: ['怀旧', '经典'], popularity: 88 },
  { term: '爷青结', slug: 'yeqingjie', meaning: '爷的青春结束了', translation: 'And so my youth ends', examples: [{ zh: '漫画完结了，爷青结。', en: 'The manga ended — and so my youth ends.' }], tags: ['怀旧'], popularity: 83 },
  { term: '有内味了', slug: 'youneiweile', meaning: '有那味儿了，像样了', translation: 'Now THAT is the vibe', examples: [{ zh: '这声线，有内味了。', en: 'That voice — now THAT is the vibe.' }], tags: ['夸赞'], popularity: 77 },
  { term: '凡尔赛', slug: 'fan-ersai', meaning: '低调炫耀', translation: 'Humble brag', examples: [{ zh: '他天天凡尔赛，烦死了。', en: 'He humble-brags every day, it is so annoying.' }], tags: ['吐槽', '炫耀'], popularity: 85 },
  { term: '老凡尔赛', slug: 'laofan-ersai', meaning: '凡尔赛大师', translation: 'Master of humble bragging', examples: [{ zh: '老凡尔赛了，装。', en: 'Such a humble-brag master.' }], tags: ['吐槽'], popularity: 78 },
  { term: '打工人', slug: 'dagongren', meaning: '上班族自嘲', translation: 'Corporate slave / 9-to-5er', examples: [{ zh: '打工人，打工魂。', en: 'Corporate slave, corporate soul.' }], tags: ['职场', '自嘲'], popularity: 90 },
  { term: '干饭人', slug: 'ganfanren', meaning: '热衷干饭（吃饭）的人', translation: 'Food warrior', examples: [{ zh: '干饭人干饭魂。', en: 'Food warriors live to eat.' }], tags: ['干饭', '自嘲'], popularity: 82 },
  { term: '尾款人', slug: 'weikuanren', meaning: '付完定金等付尾款的人', translation: 'Final-payment warrior (shopper)', examples: [{ zh: '双十一尾款人，钱包已空。', en: 'Double 11 final-payment warrior — wallet is empty.' }], tags: ['购物'], popularity: 70 },
  { term: '剁手党', slug: 'duoshoudang', meaning: '忍不住买买买的人', translation: 'Shopaholic', examples: [{ zh: '剁手党又下单了。', en: 'The shopaholic ordered again.' }], tags: ['购物'], popularity: 75 },
  { term: '月光族', slug: 'yueguangzu', meaning: '每月工资花光的人', translation: 'Living paycheck to paycheck', examples: [{ zh: '月光族月底就吃土。', en: 'Paycheck-to-paycheck people eat dirt by month end.' }], tags: ['生活'], popularity: 76 },
  { term: '社畜', slug: 'shechu', meaning: '被工作压榨的上班族', translation: 'Corporate drone', examples: [{ zh: '加班到深夜的社畜。', en: 'A corporate drone working till midnight.' }], tags: ['职场', '自嘲'], popularity: 84 },
  { term: '摸鱼', slug: 'moyu', meaning: '上班偷懒', translation: 'Slacking off', examples: [{ zh: '又在摸鱼，小心被老板抓。', en: 'Slacking off again — careful the boss does not catch you.' }], tags: ['职场'], popularity: 87 },
  { term: '划水', slug: 'huashui', meaning: '出工不出力', translation: 'Phoning it in', examples: [{ zh: '他开会全程划水。', en: 'He phoned it in the whole meeting.' }], tags: ['职场'], popularity: 79 },
  { term: '996', slug: '996', meaning: '早9晚9一周6天的工作制', translation: '9-to-9, 6 days a week', examples: [{ zh: '996 真的熬人。', en: 'Working 9-to-9 six days a week is brutal.' }], tags: ['职场', '数字'], popularity: 88 },
  { term: '007', slug: '007', meaning: '全天候无休工作', translation: '24/7 grind', examples: [{ zh: '这份工作简直 007。', en: 'This job is a 24/7 grind.' }], tags: ['职场', '数字'], popularity: 80 },
  { term: '搬砖', slug: 'banzhuan', meaning: '打工的戏称', translation: 'Grinding / working', examples: [{ zh: '不聊了，搬砖去了。', en: 'Gotta go, back to the grind.' }], tags: ['职场', '自嘲'], popularity: 78 },
  { term: '螺丝钉', slug: 'luosiding', meaning: '可有可无的小职员', translation: 'Cog in the machine', examples: [{ zh: '我只是公司的一颗螺丝钉。', en: 'I am just a cog in the machine.' }], tags: ['职场'], popularity: 74 },
  { term: '工具人', slug: 'gongjuren', meaning: '被利用的对象', translation: 'Being used / tool', examples: [{ zh: '别把我当工具人。', en: 'Do not treat me like a tool.' }], tags: ['职场', '吐槽'], popularity: 81 },
  { term: '背锅', slug: 'beiguo', meaning: '替人承担责任', translation: 'Take the fall', examples: [{ zh: '这次又是我背锅。', en: 'I have to take the fall again.' }], tags: ['职场', '吐槽'], popularity: 82 },
  { term: '甩锅', slug: 'shuaiguo', meaning: '推卸责任', translation: 'Pass the buck', examples: [{ zh: '出事了就甩锅。', en: 'When things go wrong, he passes the buck.' }], tags: ['职场', '吐槽'], popularity: 80 },
  { term: '画饼', slug: 'huabing', meaning: '开空头支票', translation: 'Pie in the sky', examples: [{ zh: '老板又在画饼了。', en: 'The boss is serving pie in the sky again.' }], tags: ['职场', '吐槽'], popularity: 83 },
  { term: '职场PUA', slug: 'zhichang-pua', meaning: '职场精神打压', translation: 'Workplace manipulation', examples: [{ zh: '天天被职场PUA，快抑郁了。', en: 'The constant workplace manipulation is driving me nuts.' }], tags: ['职场'], popularity: 79 },
  { term: '35岁危机', slug: '35suiweiji', meaning: '中年职场瓶颈', translation: 'The 35-year-old career cliff', examples: [{ zh: '程序员都有35岁危机。', en: 'Programmers all fear the 35-year-old career cliff.' }], tags: ['职场'], popularity: 76 },
  { term: '润', slug: 'run', meaning: 'run 谐音，指移民/跑路', translation: 'Get out / emigrate', examples: [{ zh: '有条件就润。', en: 'If you can, just get out.' }], tags: ['谐音', '生活'], popularity: 82 },
  { term: '提桶跑路', slug: 'titongpaolu', meaning: '辞职走人（提桶=走人梗）', translation: 'Quit and bail', examples: [{ zh: '干不下去，提桶跑路了。', en: 'Could not take it anymore — quit and bailed.' }], tags: ['职场', '自嘲'], popularity: 74 },
  { term: '摆烂', slug: 'bailan', meaning: '破罐子破摔', translation: 'Give up and go with the flow (bad way)', examples: [{ zh: '这局已经摆烂了。', en: 'This round is already lost, whatever.' }], tags: ['态度'], popularity: 85 },
  { term: '佛系', slug: 'foxi', meaning: '看淡一切、随缘', translation: 'Whatever / zen about it', examples: [{ zh: '佛系青年不争不抢。', en: 'Zen youths compete for nothing.' }], tags: ['态度'], popularity: 83 },
  { term: '网抑云', slug: 'wangyiyun', meaning: '网易云音乐，深夜emo代名词', translation: 'Late-night sad music hours', examples: [{ zh: '凌晨两点的网抑云时间。', en: 'It is 2 AM — late-night sad music hours.' }], tags: ['情绪', '音乐'], popularity: 80 },
  { term: '麻了', slug: 'male', meaning: '麻木了、心累', translation: 'So done / numb', examples: [{ zh: '天天加班，人都麻了。', en: 'Overtime every day — I am so done.' }], tags: ['情绪'], popularity: 78 },
  { term: '蚌埠住了', slug: 'bengbuzhule', meaning: '绷不住了（谐音）', translation: 'I can not hold it in', examples: [{ zh: '看到这操作蚌埠住了。', en: 'Seeing that move, I could not hold it in.' }], tags: ['谐音', '大笑'], popularity: 86 },
  { term: '绷不住了', slug: 'bengbuzhule2', meaning: '忍不住笑/情绪失控', translation: 'Lost it', examples: [{ zh: '他那个表情，我绷不住了。', en: 'His face — I completely lost it.' }], tags: ['情绪'], popularity: 84 },
  { term: '封神', slug: 'fengshen', meaning: '表现封神级，极好', translation: 'Legendary / GOAT performance', examples: [{ zh: '这场戏演技封神。', en: 'That scene was a legendary performance.' }], tags: ['夸赞'], popularity: 82 },
  { term: '天花板', slug: 'tianhuaban', meaning: '最高水平、顶级', translation: 'The ceiling / the absolute top', examples: [{ zh: '这是行业天花板。', en: 'This is the ceiling of the industry.' }], tags: ['夸赞'], popularity: 84 },
  { term: '顶流', slug: 'dingliu', meaning: '顶级流量明星', translation: 'Top-tier star / A-lister', examples: [{ zh: '他是现在的顶流。', en: 'He is the A-lister of the moment.' }], tags: ['追星'], popularity: 80 },
  { term: 'C位', slug: 'c-wei', meaning: '中心位置、主角位', translation: 'Center stage', examples: [{ zh: '海报里他站C位。', en: 'He is front and center on the poster.' }], tags: ['追星'], popularity: 78 },
  { term: '出圈', slug: 'chuquan', meaning: '破圈走红，被圈外知晓', translation: 'Break out of the niche', examples: [{ zh: '这歌彻底出圈了。', en: 'This song completely broke out of its niche.' }], tags: ['流行'], popularity: 81 },
  { term: '破圈', slug: 'poquan', meaning: '跨界出圈', translation: 'Cross over to the mainstream', examples: [{ zh: '二次元开始破圈。', en: 'Anime culture is crossing over to the mainstream.' }], tags: ['流行'], popularity: 77 },
  { term: '降维打击', slug: 'jiangweidaji', meaning: '用高维优势碾压', translation: 'Playing chess while others play checkers', examples: [{ zh: '大厂入场就是降维打击。', en: 'When the giants enter, it is chess versus checkers.' }], tags: ['流行'], popularity: 79 },
  { term: '神仙打架', slug: 'shenxiandajia', meaning: '高手过招、神仙对决', translation: 'Battle of the titans', examples: [{ zh: '今年剧集是神仙打架。', en: 'This year\'s shows are a battle of the titans.' }], tags: ['夸赞'], popularity: 78 },
  { term: '六边形战士', slug: 'liubianxing', meaning: '各方面都强的全能选手', translation: 'All-round powerhouse', examples: [{ zh: '他是乒乓六边形战士。', en: 'He is an all-round powerhouse in table tennis.' }], tags: ['夸赞'], popularity: 75 },
  { term: '全村的希望', slug: 'quancundexiwang', meaning: '被寄予厚望的人', translation: 'The hope of the whole village', examples: [{ zh: '他可是全村的希望。', en: 'He is the hope of the whole village.' }], tags: ['夸赞'], popularity: 73 },
  { term: '翻车', slug: 'fanche', meaning: '出事故、搞砸', translation: 'Blew it / crashed and burned', examples: [{ zh: '主播带货翻车了。', en: 'The livestream seller crashed and burned.' }], tags: ['吐槽'], popularity: 83 },
  { term: '塌房', slug: 'tafang', meaning: '偶像人设崩塌', translation: 'Idol scandaled / fell from grace', examples: [{ zh: '他塌房了，粉丝都跑了。', en: 'He fell from grace and fans bolted.' }], tags: ['追星', '吐槽'], popularity: 80 },
  { term: '人设崩塌', slug: 'renshebengta', meaning: '公众形象垮掉', translation: 'Image collapse', examples: [{ zh: '人设崩塌后很难翻身。', en: 'Hard to recover after an image collapse.' }], tags: ['追星', '吐槽'], popularity: 79 },
  { term: '大型翻车现场', slug: 'daxingfanche', meaning: '当众出大丑的场面', translation: 'Total trainwreck', examples: [{ zh: '发布会成了大型翻车现场。', en: 'The launch event turned into a total trainwreck.' }], tags: ['吐槽'], popularity: 76 },
  { term: '公开处刑', slug: 'gongkaichuxing', meaning: '当众出丑被围观', translation: 'Public execution (cringe)', examples: [{ zh: '当众被点名，公开处刑。', en: 'Called out in public — total cringe.' }], tags: ['吐槽'], popularity: 75 },
  { term: '辣眼睛', slug: 'layanjing', meaning: '画面太丑没法看', translation: 'Eye bleach needed', examples: [{ zh: '这穿搭辣眼睛。', en: 'That outfit needs eye bleach.' }], tags: ['吐槽'], popularity: 81 },
  { term: '毁三观', slug: 'huisanguan', meaning: '颠覆价值观', translation: 'Mind-blowing (in a bad way)', examples: [{ zh: '这剧情毁三观。', en: 'This plot is beyond messed up.' }], tags: ['吐槽'], popularity: 77 },
  { term: '三观尽毁', slug: 'sanguanjinhui', meaning: '价值观彻底颠覆', translation: 'Worldview shattered', examples: [{ zh: '看完这个我三观尽毁。', en: 'After watching that, my worldview is shattered.' }], tags: ['吐槽'], popularity: 74 },
  { term: '我裂开了', slug: 'woliekaile', meaning: '心态崩了', translation: 'I am broken', examples: [{ zh: '听到这消息我裂开了。', en: 'Hearing that news, I am broken.' }], tags: ['情绪'], popularity: 82 },
  { term: '芜湖起飞', slug: 'wuhuqifei', meaning: '兴奋起飞（方言谐音）', translation: 'Let us GO!', examples: [{ zh: '抢到票了，芜湖起飞！', en: 'Got the tickets — let us GO!' }], tags: ['谐音', '兴奋'], popularity: 80 },
  { term: '蓝瘦香菇', slug: 'lanshouxianggu', meaning: '难受想哭（方言谐音）', translation: 'So sad, wanna cry', examples: [{ zh: '加班到十点，蓝瘦香菇。', en: 'Working till 10 PM — so sad, wanna cry.' }], tags: ['谐音', '情绪'], popularity: 79 },
  { term: '好嗨哟', slug: 'haohaiyo', meaning: '好嗨啊（方言口音）', translation: 'Woo, let us party!', examples: [{ zh: '周末到了，好嗨哟。', en: 'Weekend is here — woo, let us party!' }], tags: ['谐音', '兴奋'], popularity: 77 },
  { term: '奥利给', slug: 'aoligei', meaning: '加油打气（谐音）', translation: 'Let us go! / You got this!', examples: [{ zh: '奥利给，干就完了！', en: 'You got this — just do it!' }], tags: ['谐音', '加油'], popularity: 85 },
  { term: '猴赛雷', slug: 'housailei', meaning: '好厉害（粤语）', translation: 'Impressive! (Cantonese)', examples: [{ zh: '你粤语说得猴赛雷！', en: 'Your Cantonese is impressive!' }], tags: ['方言', '夸赞'], popularity: 74 },
  { term: '得劲', slug: 'dejin', meaning: '舒服、给力（方言）', translation: 'So satisfying', examples: [{ zh: '这按摩得劲！', en: 'This massage is so satisfying!' }], tags: ['方言'], popularity: 72 },
  { term: '中不中', slug: 'zhongbuzhong', meaning: '行不行（河南方言）', translation: 'Good or not?', examples: [{ zh: '这方案中不中？', en: 'Is this plan good or not?' }], tags: ['方言'], popularity: 70 },
  { term: '莫得感情', slug: 'modedeganqing', meaning: '没有感情（方言腔）', translation: 'Cold as ice', examples: [{ zh: '打工人莫得感情。', en: 'Corporate slaves are cold as ice.' }], tags: ['方言', '自嘲'], popularity: 76 },
  { term: '我太难了', slug: 'wotainanle', meaning: '我太难了（委屈）', translation: 'Life is so hard for me', examples: [{ zh: '期末周，我太难了。', en: 'Finals week — life is so hard for me.' }], tags: ['情绪'], popularity: 88 },
  { term: '人间清醒', slug: 'renjianqingxing', meaning: '看得通透、不糊涂', translation: 'Woke / crystal clear', examples: [{ zh: '她人间清醒，从不恋爱脑。', en: 'She is crystal clear — never love-blind.' }], tags: ['夸赞'], popularity: 80 },
  { term: '恋爱脑', slug: 'lian-ainao', meaning: '满脑子只有爱情的人', translation: 'Love-obsessed / lovestruck fool', examples: [{ zh: '别当恋爱脑了姐妹。', en: 'Sis, stop being love-obsessed.' }], tags: ['恋爱', '吐槽'], popularity: 79 },
  { term: '清醒点', slug: 'qingxingdian', meaning: '劝人清醒', translation: 'Wake up!', examples: [{ zh: '清醒点，别被PUA了。', en: 'Wake up! Do not let them gaslight you.' }], tags: ['劝告'], popularity: 72 },
  { term: '格局打开', slug: 'gejudakai', meaning: '把眼光放长远', translation: 'Think bigger', examples: [{ zh: '格局打开，别计较眼前。', en: 'Think bigger — do not sweat the small stuff.' }], tags: ['劝告'], popularity: 78 },
  { term: '格局小了', slug: 'gejuxiaole', meaning: '格局不够大', translation: 'Small-minded', examples: [{ zh: '你这格局小了。', en: 'That is pretty small-minded of you.' }], tags: ['吐槽'], popularity: 76 },
  { term: 'YYGQ', slug: 'yygq', meaning: '阴阳怪气（拼音缩写）', translation: 'Passive-aggressive', examples: [{ zh: '他说话总是yygq的。', en: 'He is always passive-aggressive.' }], tags: ['缩写', '吐槽'], popularity: 81 },
  { term: '阴阳怪气', slug: 'yinyangguaiqi', meaning: '话里带刺、含沙射影', translation: 'Sarcastic and snide', examples: [{ zh: '别阴阳怪气的，有话直说。', en: 'Stop being snide — just say it.' }], tags: ['吐槽'], popularity: 82 },
  { term: '夺笋啊', slug: 'duosunna', meaning: '多损啊（谐音）', translation: 'That is so savage', examples: [{ zh: '夺笋啊，你太坏了。', en: 'That is so savage, you are terrible.' }], tags: ['谐音', '吐槽'], popularity: 77 },
  { term: '笋都被夺完了', slug: 'sundubeiduo', meaning: '损过头了', translation: 'Savagery level: over 9000', examples: [{ zh: '山上的笋都被夺完了。', en: 'All the bamboo shoots are gone — so savage.' }], tags: ['谐音', '吐槽'], popularity: 73 },
  { term: '搭讪', slug: 'dashan', meaning: '主动找人聊天', translation: 'Hit on / strike up a chat', examples: [{ zh: '他鼓起勇气去搭讪。', en: 'He plucked up the courage to hit on her.' }], tags: ['恋爱'], popularity: 71 },
  { term: '尬聊', slug: 'galiao', meaning: '尴尬地聊天', translation: 'Awkward small talk', examples: [{ zh: '跟不熟的人只能尬聊。', en: 'With strangers, it is just awkward small talk.' }], tags: ['社交'], popularity: 78 },
  { term: '社恐福音', slug: 'shekongfuyin', meaning: '社恐的救星', translation: 'A blessing for the socially anxious', examples: [{ zh: '线上点餐是社恐福音。', en: 'Ordering online is a blessing for the socially anxious.' }], tags: ['社交'], popularity: 72 },
  { term: '社牛症', slug: 'sheniuzheng', meaning: '社交牛逼症', translation: 'Ultra-extrovert energy', examples: [{ zh: '他有社牛症，见谁都能聊。', en: 'He has ultra-extrovert energy — chats with anyone.' }], tags: ['社交'], popularity: 75 },
  { term: '绝了', slug: 'juele', meaning: '太绝了（褒贬皆可）', translation: 'Unreal / insane', examples: [{ zh: '这手艺绝了！', en: 'This craft is unreal!' }], tags: ['感叹'], popularity: 86 },
  { term: '牛批', slug: 'niupi', meaning: '牛逼的谐音', translation: 'Insane / beast mode', examples: [{ zh: '这操作牛批！', en: 'That move is beast mode!' }], tags: ['谐音', '夸赞'], popularity: 84 },
  { term: '离谱', slug: 'lipu', meaning: '离谱、超出常理', translation: 'That is wild', examples: [{ zh: '这价格也太离谱了。', en: 'That price is wild.' }], tags: ['吐槽'], popularity: 85 },
  { term: '魔幻', slug: 'mohuan', meaning: '荒诞离奇', translation: 'Surreal', examples: [{ zh: '2026年的新闻太魔幻了。', en: 'The news this year is so surreal.' }], tags: ['吐槽'], popularity: 74 },
  { term: '离谱他妈给离谱开门', slug: 'lipu-kaimen', meaning: '离谱到家了', translation: 'Off the charts ridiculous', examples: [{ zh: '离谱他妈给离谱开门，离谱到家了。', en: 'This is off the charts ridiculous.' }], tags: ['吐槽'], popularity: 72 },
  { term: '我的沉默震耳欲聋', slug: 'wodechenmo', meaning: '无语到极点的表达', translation: 'My silence is deafening', examples: [{ zh: '听完他的解释，我的沉默震耳欲聋。', en: 'After his explanation, my silence was deafening.' }], tags: ['吐槽'], popularity: 80 },
  { term: '泰裤辣', slug: 'taikula', meaning: '太酷啦（谐音）', translation: 'So cool!', examples: [{ zh: '这造型泰裤辣！', en: 'That look is so cool!' }], tags: ['谐音', '夸赞'], popularity: 76 },
  { term: '好家伙', slug: 'haojiahuo', meaning: '感叹词：好家伙（惊叹）', translation: 'Well, well, well', examples: [{ zh: '好家伙，你居然会这个。', en: 'Well, well, well — you can actually do that.' }], tags: ['感叹'], popularity: 78 },
  { term: '栓住了', slug: 'shuanzhule', meaning: '被吸引住、上头', translation: 'Hooked', examples: [{ zh: '这剧情把我栓住了。', en: 'This plot has me hooked.' }], tags: ['情绪'], popularity: 70 },
  { term: '被种草了', slug: 'beizhongcaole', meaning: '被安利、想买', translation: 'Got me tempted', examples: [{ zh: '看测评被种草了。', en: 'That review got me tempted.' }], tags: ['购物'], popularity: 79 },
  { term: '种草', slug: 'zhongcao', meaning: '安利别人买', translation: 'Sell someone on it', examples: [{ zh: '她又来种草了。', en: 'She is selling us on it again.' }], tags: ['购物'], popularity: 83 },
  { term: '拔草', slug: 'bacao', meaning: '打消购买念头', translation: 'Talk yourself out of it', examples: [{ zh: '看了差评，拔草了。', en: 'Read the bad reviews — talked myself out of it.' }], tags: ['购物'], popularity: 78 },
  { term: '安利', slug: 'anli', meaning: '强烈推荐', translation: 'Shill for / highly recommend', examples: [{ zh: '疯狂安利这部电影。', en: 'I am shilling hard for this movie.' }], tags: ['购物', '推荐'], popularity: 84 },
  { term: '恰饭', slug: 'qiafan', meaning: '接广告赚钱（恰=吃）', translation: 'Sponsored (content)', examples: [{ zh: '这期视频是恰饭的。', en: 'This video is sponsored.' }], tags: ['自媒体'], popularity: 77 },
  { term: '白嫖', slug: 'baipiao', meaning: '不花钱白拿', translation: 'Free-ride / freeload', examples: [{ zh: '白嫖怪又来了。', en: 'The freeloader is here again.' }], tags: ['网络'], popularity: 82 },
  { term: '薅羊毛', slug: 'haoyangmao', meaning: '占商家便宜', translation: 'Gaming the deals', examples: [{ zh: '又在薅平台羊毛。', en: 'Gaming the platform deals again.' }], tags: ['购物'], popularity: 80 },
  { term: '捡漏', slug: 'jianlou', meaning: '低价买到好货', translation: 'Steal of a deal', examples: [{ zh: '这个价真是捡漏了。', en: 'At this price, it is a steal of a deal.' }], tags: ['购物'], popularity: 76 },
  { term: '秒杀', slug: 'miaosha', meaning: '限时抢购', translation: 'Flash sale', examples: [{ zh: '秒杀价手慢无。', en: 'Flash sale — slow hands miss out.' }], tags: ['购物'], popularity: 74 },
  { term: '割韭菜', slug: 'gejiucai', meaning: '收割普通消费者/散户', translation: 'Fleece the masses', examples: [{ zh: '这项目又来割韭菜了。', en: 'This scheme is fleecing the masses again.' }], tags: ['吐槽'], popularity: 81 },
  { term: '韭菜', slug: 'jiucai', meaning: '被收割的普通人', translation: 'The fleeced masses', examples: [{ zh: '散户都是韭菜。', en: 'Retail investors are the fleeced masses.' }], tags: ['吐槽'], popularity: 79 },
  { term: '智商税', slug: 'zhishangshui', meaning: '为营销噱头交的钱', translation: 'Stupidity tax', examples: [{ zh: '买这个纯属交智商税。', en: 'Buying that is pure stupidity tax.' }], tags: ['吐槽'], popularity: 83 },
  { term: '智商不在线', slug: 'zhishangbuzaixian', meaning: '犯傻', translation: 'Brain not in gear', examples: [{ zh: '我今天智商不在线。', en: 'My brain is not in gear today.' }], tags: ['自嘲'], popularity: 74 },
  { term: '有被冒犯到', slug: 'youbeimaofandao', meaning: '感到被冒犯', translation: 'I felt that / personally attacked', examples: [{ zh: '这段话有被冒犯到。', en: 'That line felt like a personal attack.' }], tags: ['情绪'], popularity: 79 },
  { term: '破大防', slug: 'podafang', meaning: '彻底破防', translation: 'Completely shattered', examples: [{ zh: '这首歌让我破大防。', en: 'This song completely shattered me.' }], tags: ['情绪'], popularity: 81 },
  { term: '天塌了', slug: 'tiantale', meaning: '重大打击', translation: 'My world collapsed', examples: [{ zh: '听到这消息天塌了。', en: 'Hearing that, my world collapsed.' }], tags: ['情绪'], popularity: 76 },
  { term: '不是吧', slug: 'bushiba', meaning: '不会吧（惊讶/无语）', translation: 'No way', examples: [{ zh: '不是吧，这也能输？', en: 'No way, we lost to that?' }], tags: ['感叹'], popularity: 75 },
  { term: '真的会谢', slug: 'zhendehuixie', meaning: '真的会谢（无语+感谢反讽）', translation: 'Thanks a lot (sarcastic)', examples: [{ zh: '周一就加班，真的会谢。', en: 'Overtime on a Monday — thanks a lot.' }], tags: ['反讽'], popularity: 78 },
  { term: '尊嘟假嘟', slug: 'zundujiadu', meaning: '真的假的（卖萌谐音）', translation: 'For real, for real?', examples: [{ zh: '尊嘟假嘟，你中奖了？', en: 'For real? You actually won?' }], tags: ['谐音'], popularity: 74 },
  { term: '那必须的', slug: 'nabixude', meaning: '当然、肯定的', translation: 'You bet', examples: [{ zh: '那必须的，我可是专业的。', en: 'You bet, I am a professional.' }], tags: ['表态'], popularity: 72 },
  { term: '无语凝噎', slug: 'wuyuningye', meaning: '无语到说不出话（文雅版）', translation: 'Lost for words', examples: [{ zh: '看到账单，无语凝噎。', en: 'Seeing the bill, I was lost for words.' }], tags: ['情绪'], popularity: 73 },
  { term: '报一丝', slug: 'baoyisi', meaning: '不好意思（谐音）', translation: 'My bad / sorry (cute)', examples: [{ zh: '报一丝，堵车来晚了。', en: 'Sorry, traffic made me late.' }], tags: ['谐音'], popularity: 71 },
  { term: '一整个爱住', slug: 'yizhengeaizhu', meaning: '彻底爱上', translation: 'Totally in love with it', examples: [{ zh: '这家店一整个爱住。', en: 'Totally in love with this place.' }], tags: ['夸赞'], popularity: 72 },
  { term: '心动预警', slug: 'xindongyujing', meaning: '提醒会心动', translation: 'Heart-attack warning', examples: [{ zh: '前方心动预警。', en: 'Heart-attack warning ahead.' }], tags: ['夸赞'], popularity: 70 },
  { term: '一整个拿捏住', slug: 'yizhengnanie', meaning: '完全掌控', translation: 'Got it fully locked', examples: [{ zh: '这个场子我拿捏住了。', en: 'I have this whole room locked.' }], tags: ['夸赞'], popularity: 70 },
  { term: '原地结婚', slug: 'yuandijiehun', meaning: '太配了，原地结婚', translation: 'Just get married already', examples: [{ zh: '他俩好配，原地结婚！', en: 'They are perfect together — just get married already!' }], tags: ['夸赞'], popularity: 74 },
  { term: '磕到了', slug: 'kedaole', meaning: '嗑CP嗑到了糖', translation: 'Shipping them so hard', examples: [{ zh: '看他们互动，磕到了。', en: 'Watching them interact — shipping them so hard.' }], tags: ['追星'], popularity: 76 },
  { term: 'kswl', slug: 'kswl', meaning: '磕死我了（拼音缩写）', translation: 'Shipping them to death', examples: [{ zh: '这CP互动 kswl！', en: 'This pairing — shipping them to death!' }], tags: ['缩写', '追星'], popularity: 82 },
  { term: 'CP感', slug: 'cp-gan', meaning: '情侣配对感', translation: 'Chemistry', examples: [{ zh: '他俩CP感太强了。', en: 'Their chemistry is off the charts.' }], tags: ['追星'], popularity: 77 },
  { term: '磕CP', slug: 'kecp', meaning: '嗑CP、粉配对', translation: 'Shipping a pairing', examples: [{ zh: '我又磕了一对CP。', en: 'I am shipping another pairing now.' }], tags: ['追星'], popularity: 79 },
  { term: 'yyds梗', slug: 'yydsgeng', meaning: 'YYDS相关玩梗', translation: 'The "GOAT" meme', examples: [{ zh: '万物皆可YYDS。', en: 'Everything can be called GOAT.' }], tags: ['梗'], popularity: 80 },
  { term: '梗王', slug: 'gengwang', meaning: '造梗/玩梗高手', translation: 'Meme king', examples: [{ zh: '他是综艺界的梗王。', en: 'He is the meme king of variety shows.' }], tags: ['夸赞'], popularity: 72 },
  { term: '烂梗', slug: 'langeng', meaning: '不好笑的梗', translation: 'Dead meme / cringe joke', examples: [{ zh: '别玩烂梗了。', en: 'Stop with the dead memes.' }], tags: ['吐槽'], popularity: 74 },
  { term: '老梗', slug: 'laogeng', meaning: '旧梗、过时梗', translation: 'Old meme', examples: [{ zh: '这都老梗了。', en: 'That is an old meme now.' }], tags: ['吐槽'], popularity: 71 },
  { term: '玩梗', slug: 'wangeng', meaning: '用梗开玩笑', translation: 'Drop a meme reference', examples: [{ zh: '别乱玩梗。', en: 'Do not drop meme references randomly.' }], tags: ['网络'], popularity: 76 },
  { term: '整活', slug: 'zhenghuo', meaning: '搞事情、整节目效果', translation: 'Pull a stunt', examples: [{ zh: '他又开始整活了。', en: 'He is pulling another stunt.' }], tags: ['网络'], popularity: 78 },
  { term: '节目效果', slug: 'jiemuxiaoguo', meaning: '综艺效果拉满', translation: 'Great TV', examples: [{ zh: '这反应节目效果拉满。', en: 'That reaction is great TV.' }], tags: ['夸赞'], popularity: 73 },
  { term: '名场面', slug: 'mingchangmian', meaning: '经典名场面', translation: 'Iconic scene', examples: [{ zh: '这场戏是名场面。', en: 'That scene is iconic.' }], tags: ['夸赞'], popularity: 80 },
  { term: '出戏', slug: 'chuxi', meaning: '跳戏、出戏', translation: 'Pulled out of the moment', examples: [{ zh: '他的口音让我出戏。', en: 'His accent pulled me out of the moment.' }], tags: ['影视'], popularity: 74 },
  { term: '入戏', slug: 'ruxi', meaning: '沉浸角色', translation: 'In character', examples: [{ zh: '他演得太入戏了。', en: 'He was so in character.' }], tags: ['影视'], popularity: 72 },
  { term: '飙戏', slug: 'biaoxi', meaning: '演技对决', translation: 'Acting showdown', examples: [{ zh: '两位影帝飙戏太精彩。', en: 'Two legends in an acting showdown — amazing.' }], tags: ['影视'], popularity: 73 },
  { term: '演技炸裂', slug: 'yanjizhalie', meaning: '演技爆炸好', translation: 'Explosive performance', examples: [{ zh: '这场哭戏演技炸裂。', en: 'That crying scene was an explosive performance.' }], tags: ['夸赞'], popularity: 78 },
  { term: '尬演', slug: 'gayan', meaning: '尴尬的表演', translation: 'Cringe acting', examples: [{ zh: '这段尬演没眼看。', en: 'That cringe acting is unwatchable.' }], tags: ['吐槽'], popularity: 75 },
  { term: '烂片', slug: 'lanpian', meaning: '烂电影', translation: 'Trash movie', examples: [{ zh: '又一部烂片。', en: 'Another trash movie.' }], tags: ['影视', '吐槽'], popularity: 74 },
  { term: '神作', slug: 'shenzuo', meaning: '神级作品', translation: 'Masterpiece', examples: [{ zh: '这部是神作。', en: 'This one is a masterpiece.' }], tags: ['影视', '夸赞'], popularity: 76 },
  { term: '追剧', slug: 'zhuiju', meaning: '追着看剧', translation: 'Binge-watch / follow a show', examples: [{ zh: '最近在追这部剧。', en: 'I am following this show right now.' }], tags: ['影视'], popularity: 75 },
  { term: '弃剧', slug: 'qiju', meaning: '放弃追剧', translation: 'Dropped the show', examples: [{ zh: '剧情太拖，弃剧了。', en: 'The plot drags — dropped the show.' }], tags: ['影视'], popularity: 72 },
  { term: '剧透', slug: 'jutou', meaning: '提前透露剧情', translation: 'Spoiler', examples: [{ zh: '别剧透！', en: 'No spoilers!' }], tags: ['影视'], popularity: 79 },
  { term: '弹幕', slug: 'danmu', meaning: '视频评论飘屏', translation: 'Bullet comments', examples: [{ zh: '弹幕比剧还好看。', en: 'The bullet comments are better than the show.' }], tags: ['影视'], popularity: 78 },
  { term: '打卡', slug: 'daka', meaning: '签到、网红地打卡', translation: 'Check in', examples: [{ zh: '去新店打卡了。', en: 'Checked in at the new place.' }], tags: ['生活'], popularity: 80 },
  { term: '探店', slug: 'tandian', meaning: '去店里探店测评', translation: 'Food/place review hunt', examples: [{ zh: '周末去探店。', en: 'Going on a review hunt this weekend.' }], tags: ['生活'], popularity: 76 },
  { term: '网红店', slug: 'wanghongdian', meaning: '网上爆火的店', translation: 'Instagram-famous spot', examples: [{ zh: '网红店排队两小时。', en: 'Two-hour queue at that Instagram-famous spot.' }], tags: ['生活'], popularity: 75 },
  { term: '网红', slug: 'wanghong', meaning: '网络红人', translation: 'Internet celebrity', examples: [{ zh: '他是美食网红。', en: 'He is a food internet celebrity.' }], tags: ['网络'], popularity: 80 },
  { term: '爆火', slug: 'baohuo', meaning: '突然爆红', translation: 'Blew up', examples: [{ zh: '这首歌突然爆火。', en: 'This song suddenly blew up.' }], tags: ['网络'], popularity: 79 },
  { term: '过气', slug: 'guoqi', meaning: '过时、不火了', translation: 'Past their prime', examples: [{ zh: '他早就过气了。', en: 'He is long past his prime.' }], tags: ['网络'], popularity: 76 },
  { term: '凉凉', slug: 'liangliang', meaning: '完蛋了、没戏了', translation: 'Done for', examples: [{ zh: '这项目凉凉了。', en: 'This project is done for.' }], tags: ['吐槽'], popularity: 81 },
  { term: '洗白', slug: 'xibai', meaning: '洗清负面形象', translation: 'Spin the narrative', examples: [{ zh: '别想洗白。', en: 'Do not even try to spin the narrative.' }], tags: ['吐槽'], popularity: 77 },
  { term: '实锤', slug: 'shichui', meaning: '证据坐实', translation: 'Receipts / confirmed', examples: [{ zh: '这事被实锤了。', en: 'The receipts are out — confirmed.' }], tags: ['吐槽'], popularity: 78 },
  { term: '吃瓜群众', slug: 'chiguaqunzhong', meaning: '围观群众', translation: 'Bystanders / tea-sippers', examples: [{ zh: '吃瓜群众表示很满意。', en: 'The tea-sippers are very satisfied.' }], tags: ['八卦'], popularity: 79 },
  { term: '瓜田', slug: 'guatian', meaning: '八卦密集的地方', translation: 'Drama central', examples: [{ zh: '最近瓜田大丰收。', en: 'Drama central has a bumper crop lately.' }], tags: ['八卦'], popularity: 72 },
  { term: '大瓜', slug: 'dagua', meaning: '大八卦', translation: 'Huge tea', examples: [{ zh: '今天爆了个大瓜。', en: 'Huge tea dropped today.' }], tags: ['八卦'], popularity: 77 },
  { term: '料', slug: 'liao', meaning: '爆料信息', translation: 'The scoop / dirt', examples: [{ zh: '他手里有料。', en: 'He has the dirt.' }], tags: ['八卦'], popularity: 71 },
  { term: '爆料', slug: 'baoliao', meaning: '爆出内幕', translation: 'Drop the scoop', examples: [{ zh: '有人爆料了内幕。', en: 'Someone dropped the scoop.' }], tags: ['八卦'], popularity: 74 },
  { term: '锤', slug: 'chui', meaning: '实锤、证据', translation: 'The receipts', examples: [{ zh: '锤来了，跑不掉了。', en: 'The receipts are here — no escape.' }], tags: ['八卦'], popularity: 73 },
  { term: '反转', slug: 'fanzhuan', meaning: '剧情大反转', translation: 'Plot twist', examples: [{ zh: '这瓜还有反转。', en: 'This drama has another plot twist.' }], tags: ['八卦'], popularity: 78 },
  { term: '大冤种', slug: 'dayuanzhong', meaning: '冤大头', translation: 'Sucker / scapegoat', examples: [{ zh: '我又成大冤种了。', en: 'I ended up being the sucker again.' }], tags: ['自嘲'], popularity: 79 },
  { term: '精神内耗', slug: 'jingshenneihao', meaning: '自我消耗、想太多', translation: 'Mental drain / overthinking spiral', examples: [{ zh: '别精神内耗了，想开点。', en: 'Stop the mental drain — let it go.' }], tags: ['情绪'], popularity: 82 },
];