// 梗词条批量数据 #001（25 条）— 运营侧产出，2026-08-09
// slug 已核验与 meme-data.ts 现有 200 条零冲突；标签复用现有 44 个分类
import type { MemeSeed } from './meme-data';

export const memeBatch001: MemeSeed[] = [
  { term: '已老实', slug: 'yi-laoshi', meaning: '网络流行语，认怂服软后的表态，常配「已老实，求放过」梗图。', translation: '"I\'ve learned my lesson." / "Being good now, I swear."', examples: [{ zh: '兄弟我已经老实了，别搞我了。', en: 'Bro, I\'ve learned my lesson — please cut me some slack.' }], tags: ['表态', '网络', '自嘲'], popularity: 55 },
  { term: '班味', slug: 'ban-wei', meaning: '打工人被工作状态腌入味，一眼看出是上班族的气质。', translation: '"that burnt-out 9-to-5 aura"', examples: [{ zh: '地铁上全是班味十足的打工人。', en: 'The subway is full of commuters radiating that burnt-out 9-to-5 aura.' }], tags: ['职场', '自嘲', '吐槽'], popularity: 70 },
  { term: '电子榨菜', slug: 'dianzi-jiangcai', meaning: '吃饭时当下饭菜看的视频、直播或音频，没有就吃不下饭。', translation: '"digital comfort food" / "background show while eating"', examples: [{ zh: '这部下饭剧是我的电子榨菜。', en: 'This comfort show is my digital pickled-veg — I can\'t eat without it.' }], tags: ['生活', '网络', '影视'], popularity: 50 },
  { term: '天选打工人', slug: 'tianxuan-dagongren', meaning: '自嘲自己是被选中注定打工的命，带点无奈和幽默。', translation: '"the chosen one of the grind" / "born to clock in"', examples: [{ zh: '早起挤地铁，天选打工人没跑了。', en: 'Squeezing onto the metro at dawn — guess I\'m the chosen one of the grind.' }], tags: ['职场', '自嘲', '吐槽'], popularity: 45 },
  { term: '牛马', slug: 'niu-ma', meaning: '牛和马，比喻被压榨的普通打工人，多为自嘲。', translation: '"beasts of burden" / "corporate draft animals"', examples: [{ zh: '牛马的一天又开始了。', en: 'Another day as a beast of burden begins.' }], tags: ['职场', '自嘲', '吐槽'], popularity: 65 },
  { term: '全职儿女', slug: 'quan-zhi-ernv', meaning: '毕业后住家陪父母、承担家庭事务的年轻人，自嘲式称呼。', translation: '"full-time son/daughter" (living with and caring for parents)', examples: [{ zh: '找不到工作，先当全职儿女吧。', en: 'Can\'t land a job yet, so I\'ll be a full-time son for a while.' }], tags: ['社会现象', '生活'], popularity: 40 },
  { term: '显眼包', slug: 'xianyan-bao', meaning: '爱出风头、引人注目的家伙，褒贬看语境，常带调侃。', translation: '"attention seeker" / "the show-off"', examples: [{ zh: '全场就他一个显眼包。', en: 'He\'s the one attention seeker in the whole room.' }], tags: ['吐槽', '社交', '性格'], popularity: 75 },
  { term: '遥遥领先', slug: 'yaoyao-lingxian', meaning: '因发布会金句出圈，现广泛用于夸产品/表现。', translation: '"leading by a mile" / "way ahead of the pack"', examples: [{ zh: '这性能在同行里遥遥领先。', en: 'Its performance is leading the pack by a mile.' }], tags: ['夸赞', '网络', '表态'], popularity: 50 },
  { term: 'City不City', slug: 'city-bucity', meaning: '洋气不洋气、有没有都市感，网红句式「好City啊」。', translation: '"Is it city?" / "How chic is that?"', examples: [{ zh: '这家咖啡店好City啊。', en: 'This café is so city — total chic vibes.' }], tags: ['网络', '流行', '夸赞'], popularity: 60 },
  { term: '科目三', slug: 'kemusan', meaning: '爆火网络舞蹈「科目三」，源自驾考梗，配曲《一笑江湖》。', translation: '"Subject Three" (the viral dance)', examples: [{ zh: '婚礼上他跳了一段科目三。', en: 'He busted out a Subject Three dance at the wedding.' }], tags: ['音乐', '流行', '网络'], popularity: 55 },
  { term: '特种兵式旅游', slug: 'tezhongbing-lvyou', meaning: '极限打卡、时间紧任务重的旅游方式，主打快节奏。', translation: '"special-forces tourism" / "speedrun sightseeing"', examples: [{ zh: '大学生特种兵式旅游，一天打卡八个景点。', en: 'College students on special-forces tourism, hitting eight sights in one day.' }], tags: ['生活', '流行', '社会现象'], popularity: 45 },
  { term: '南方小土豆', slug: 'nanfang-xiaotudou', meaning: '东北网友对南方游客的昵称，形容娇小可爱，含热情好客之意。', translation: '"little southern potatoes" (affectionate nickname for southern tourists)', examples: [{ zh: '欢迎南方小土豆来哈尔滨玩！', en: 'Welcome to Harbin, little southern potatoes!' }], tags: ['称呼', '萌', '网络'], popularity: 50 },
  { term: '松弛感', slug: 'songchi-gan', meaning: '从容不迫、不紧绷的生活状态，被追捧的情绪风格。', translation: '"chill vibes" / "relaxed composure"', examples: [{ zh: '她身上有种天生的松弛感。', en: 'She has this natural, effortless chill.' }], tags: ['生活态度', '态度', '性格'], popularity: 65 },
  { term: '浓人淡人', slug: 'nongren-danren', meaning: '网络人格分类：浓人=高能量外放，淡人=低欲望平静。', translation: '"intense vs. low-key person"', examples: [{ zh: '我是淡人，他是浓人，我俩互补。', en: 'I\'m the low-key type, he\'s the intense one — we balance each other out.' }], tags: ['性格', '网络'], popularity: 55 },
  { term: '偷感', slug: 'tou-gan', meaning: '偷偷摸摸做事怕被发现的心理感觉，形容小心翼翼。', translation: '"sneaky energy" / "the sneak vibe"', examples: [{ zh: '在办公室摸鱼有种偷感。', en: 'Slacking off at the office gives me serious sneaky energy.' }], tags: ['情绪', '网络', '自嘲'], popularity: 60 },
  { term: '脆皮大学生', slug: 'cuipi-daxuesheng', meaning: '自嘲身体脆弱的年轻人，一碰就伤，戏称「脆皮」。', translation: '"crispy college students" (fragile, injury-prone)', examples: [{ zh: '又脆皮了，打个喷嚏腰闪了。', en: 'So crispy — I threw my back out sneezing.' }], tags: ['自嘲', '吐槽', '社会现象'], popularity: 60 },
  { term: '断亲', slug: 'duan-qin', meaning: '年轻人与亲戚逐渐疏远、减少往来，反映社交观念变化。', translation: '"cutting ties with relatives"', examples: [{ zh: '越来越多年轻人选择断亲。', en: 'More and more young people are cutting ties with extended relatives.' }], tags: ['社会现象', '情绪'], popularity: 45 },
  { term: '嘴替', slug: 'zuo-ti', meaning: '替别人说出心声的人，「你就是我的嘴替」。', translation: '"my mouthpiece" / "says it for me"', examples: [{ zh: '这条评论简直是我的嘴替。', en: 'That comment is literally my mouthpiece.' }], tags: ['夸赞', '社交', '网络'], popularity: 65 },
  { term: '情绪价值', slug: 'qingxu-jiazhi', meaning: '给人带来情感支持、情绪体验的价值，常指陪伴与共情。', translation: '"emotional value" / "emotional support"', examples: [{ zh: '他特别会提供情绪价值。', en: 'He\'s great at offering emotional support.' }], tags: ['恋爱', '社交', '夸赞'], popularity: 70 },
  { term: '谁懂啊', slug: 'shei-dong-a', meaning: '求共鸣的口头禅，「谁能懂我这种感觉」。', translation: '"who gets it?" / "anyone feel me?"', examples: [{ zh: '这种快乐谁懂啊！', en: 'Who gets how happy this makes me?!' }], tags: ['情绪', '感叹', '网络'], popularity: 50 },
  { term: '泼天的富贵', slug: 'potian-de-fugui', meaning: '突如其来的巨大财富或好运，也用于调侃。', translation: '"a flood of fortune"', examples: [{ zh: '这波泼天的富贵终于轮到我了。', en: 'This flood of fortune has finally come my way.' }], tags: ['夸赞', '感叹', '网络'], popularity: 55 },
  { term: '命运的齿轮开始转动', slug: 'mingyun-de-chilun', meaning: '形容人生关键转折点，叙事感十足的网络金句。', translation: '"the wheel of fate began to turn"', examples: [{ zh: '那年夏天，命运的齿轮开始转动。', en: 'That summer, the wheel of fate began to turn.' }], tags: ['情绪', '怀旧', '网络'], popularity: 40 },
];