// 梗词条批量数据 #002（18 条）— 运营侧产出，2026-08-09
// term + slug 双重核验，与 meme-data.ts(200) + meme-batch-001(22) 零冲突
import type { MemeSeed } from './meme-data';

export const memeBatch002: MemeSeed[] = [
  { term: '已读乱回', slug: 'yidu-luanhui', meaning: '看到消息不回，或回一句毫无关系的内容，敷衍式社交回应。', translation: '"read but replied with nonsense" / "responded off-topic"', examples: [{ zh: '他消息已读乱回，明显在敷衍。', en: 'He read my message but replied with total nonsense — clearly brushing me off.' }], tags: ['社交', '吐槽'], popularity: 45 },
  { term: '已读不回', slug: 'yidu-buhui', meaning: '看到消息却不回复，社交冷暴力的一种。', translation: '"left on read"', examples: [{ zh: '消息发出去三天了，还是已读不回。', en: 'It\'s been three days and I\'m still left on read.' }], tags: ['社交', '吐槽'], popularity: 60 },
  { term: '电子木鱼', slug: 'dianzi-muyu', meaning: '敲木鱼 App/网页，主打「敲一下积功德」的解压玩法。', translation: '"digital wooden fish" (a stress-relief tapping app)', examples: [{ zh: '压力大的时候敲敲电子木鱼。', en: 'When stress hits, I tap my digital wooden fish.' }], tags: ['生活', '网络'], popularity: 45 },
  { term: '废话文学', slug: 'feihua-wenxue', meaning: '说了一堆等于没说的文案，「听君一席话，如听一席话」。', translation: '"nonsense literature" / "tautological memes"', examples: [{ zh: '你这段废话文学我竟无法反驳。', en: 'Your nonsense literature is somehow impossible to argue with.' }], tags: ['网络', '梗'], popularity: 50 },
  { term: '发疯文学', slug: 'fafeng-wenxue', meaning: '用夸张癫狂的文字宣泄情绪，常配大段标点和感叹号。', translation: '"unhinged literature" / "screaming-into-the-void posts"', examples: [{ zh: '深夜发疯文学，把情绪全倒出来。', en: 'Posting some unhinged literature at 2am to let it all out.' }], tags: ['网络', '情绪'], popularity: 55 },
  { term: '精神状态良好', slug: 'jingshen-zhuangtai-lianghao', meaning: '反讽式自述，通常实际状态并不良好。', translation: '"in a perfectly stable mental state" (ironic)', examples: [{ zh: '别担心，我精神状态良好（才怪）。', en: 'Don\'t worry, I\'m in a perfectly stable mental state (not).' }], tags: ['自嘲', '情绪'], popularity: 55 },
  { term: '淡淡的死感', slug: 'dandande-sigan', meaning: '形容疲惫到生无可恋、毫无波澜的状态。', translation: '"a faint sense of being dead inside"', examples: [{ zh: '周五下班，整个人有种淡淡的死感。', en: 'Leaving work on Friday with that faint sense of being dead inside.' }], tags: ['情绪', '自嘲'], popularity: 60 },
  { term: '硬控', slug: 'ying-kong', meaning: '原为游戏控制技能，现指被某事物牢牢吸引无法自拔。', translation: '"hard CC" / "utterly captivated"', examples: [{ zh: '这段舞蹈直接硬控我三分钟。', en: 'That dance had me in hard CC for three straight minutes.' }], tags: ['网络', '游戏'], popularity: 50 },
  { term: '死嘴快说', slug: 'sizui-kuai-shuo', meaning: '催促对方把话说出来，「你的嘴倒是快说啊」。', translation: '"spit it out!" / "out with it!"', examples: [{ zh: '你死嘴快说，到底发生什么了？', en: 'Spit it out — what happened?!' }], tags: ['网络', '催促'], popularity: 45 },
  { term: '包的', slug: 'bao-de', meaning: '「包在我身上」的省略版，表示保证、稳了。', translation: '"for sure!" / "I got you — guaranteed"', examples: [{ zh: '这事交给我，包的。', en: 'Leave it to me — I got you, guaranteed.' }], tags: ['网络', '表态'], popularity: 40 },
  { term: '老登', slug: 'lao-deng', meaning: '对中老年男性的戏谑/贬义称呼，网络吵架高频词。', translation: '"old geezer" (slang, mildly derogatory)', examples: [{ zh: '这群老登又在指手画脚了。', en: 'Those old geezers are bossing everyone around again.' }], tags: ['吐槽', '称呼'], popularity: 65 },
  { term: '小登', slug: 'xiao-deng', meaning: '与「老登」对应，指年轻一代，多用于网络代际互怼。', translation: '"young buck" / "the youngsters"', examples: [{ zh: '小登们根本不懂我们当年的玩法。', en: 'These young bucks have no idea how we did it back then.' }], tags: ['称呼', '网络'], popularity: 50 },
  { term: '翻红', slug: 'fan-hong', meaning: '过气后重新走红，常指艺人或作品。', translation: '"made a comeback" / "rediscovered fame"', examples: [{ zh: '这首歌因为短视频翻红了。', en: 'The song made a comeback thanks to short videos.' }], tags: ['追星', '影视'], popularity: 45 },
  { term: '无效社交', slug: 'wu-xiao-shejiao', meaning: '毫无价值和收获的社交活动。', translation: '"pointless socializing" / "dead-weight networking"', examples: [{ zh: '与其无效社交，不如回家睡觉。', en: 'Rather than pointless socializing, I\'d rather sleep.' }], tags: ['社交', '生活'], popularity: 55 },
  { term: '搞钱', slug: 'gao-qian', meaning: '一门心思赚钱，「搞钱才是硬道理」。', translation: '"hustle for money" / "make that bread"', examples: [{ zh: '别谈理想了，先搞钱。', en: 'Skip the ideals — first, let\'s make that bread.' }], tags: ['职场', '自嘲'], popularity: 60 },
  { term: '妈生脸', slug: 'ma-sheng-lian', meaning: '天生自然的脸，夸人没整容也好看。', translation: '"natural-born face" / "born with it"', examples: [{ zh: '她这妈生脸比整容脸自然多了。', en: 'Her natural-born face looks way more natural than surgery.' }], tags: ['夸赞', '追星'], popularity: 40 },
  { term: '孔乙己的长衫', slug: 'kong-yi-ji-de-changshan', meaning: '借鲁迅小说比喻放不下学历身段、不愿低就的处境。', translation: '"Kong Yiji\'s long gown" (refusing to lower one\'s pride)', examples: [{ zh: '脱不下孔乙己的长衫，又撑不起梦想。', en: 'Can\'t take off Kong Yiji\'s long gown, but can\'t afford the dream either.' }], tags: ['社会现象', '自嘲'], popularity: 55 },
  { term: '45度人生', slug: 'sishiwudu-rensheng', meaning: '介于「躺平」和「内卷」之间的折中状态。', translation: '"the 45-degree life" (between lying flat and burning out)', examples: [{ zh: '卷不动也躺不平，就过 45 度人生吧。', en: 'Too tired to grind, too restless to lie flat — living the 45-degree life.' }], tags: ['职场', '自嘲', '社会现象'], popularity: 50 },
];